# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Professional Countdowns"
client_id = "0d47d73bf2eafabe427f4ddba149cca4"
application_url = "https://newer-indicating-processed-lazy.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_metaobject_definitions,read_metaobjects,write_metaobjects"

[auth]
redirect_urls = [
  "https://newer-indicating-processed-lazy.trycloudflare.com/auth/callback",
  "https://newer-indicating-processed-lazy.trycloudflare.com/auth/shopify/callback",
  "https://newer-indicating-processed-lazy.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "kalliedev.myshopify.com"
